/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:57b86f14-c01e-49bd-a489-d15051b02088",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xvPDkRh2F",
    "aws_user_pools_web_client_id": "4p9gco3vp0dfto24fi3js4so3h",
    "oauth": {
        "domain": "2rxw5e45aoa8-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://192.168.1.24:19000/,exp://192.168.1.10:19000/",
        "redirectSignOut": "exp://192.168.1.24:19000/,exp://192.168.1.10:19000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://h676ko3ii5fwlaktscarqwmv3e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-co4cfv4u3vecvpchcfj65mkfqy",
    "aws_cloud_logic_custom": [
        {
            "name": "trumoldRestApi",
            "endpoint": "https://hfn77gx8e2.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "trumoldbucket34651-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
