/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateNotification = /* GraphQL */ `
  subscription OnCreateNotification(
    $filter: ModelSubscriptionNotificationFilterInput
  ) {
    onCreateNotification(filter: $filter) {
      id
      url
      from {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      to {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      title
      message
      messageType
      createdAt
      updatedAt
      notificationFromId
      notificationToId
      __typename
    }
  }
`;
export const onUpdateNotification = /* GraphQL */ `
  subscription OnUpdateNotification(
    $filter: ModelSubscriptionNotificationFilterInput
  ) {
    onUpdateNotification(filter: $filter) {
      id
      url
      from {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      to {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      title
      message
      messageType
      createdAt
      updatedAt
      notificationFromId
      notificationToId
      __typename
    }
  }
`;
export const onDeleteNotification = /* GraphQL */ `
  subscription OnDeleteNotification(
    $filter: ModelSubscriptionNotificationFilterInput
  ) {
    onDeleteNotification(filter: $filter) {
      id
      url
      from {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      to {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      title
      message
      messageType
      createdAt
      updatedAt
      notificationFromId
      notificationToId
      __typename
    }
  }
`;
export const onCreateMessage = /* GraphQL */ `
  subscription OnCreateMessage($filter: ModelSubscriptionMessageFilterInput) {
    onCreateMessage(filter: $filter) {
      id
      text
      user {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      chatRoom {
        id
        createdAt
        updatedAt
        chatRoomMemberId
        chatRoomCoachId
        __typename
      }
      createdAt
      updatedAt
      messageUserId
      messageChatRoomId
      __typename
    }
  }
`;
export const onUpdateMessage = /* GraphQL */ `
  subscription OnUpdateMessage($filter: ModelSubscriptionMessageFilterInput) {
    onUpdateMessage(filter: $filter) {
      id
      text
      user {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      chatRoom {
        id
        createdAt
        updatedAt
        chatRoomMemberId
        chatRoomCoachId
        __typename
      }
      createdAt
      updatedAt
      messageUserId
      messageChatRoomId
      __typename
    }
  }
`;
export const onDeleteMessage = /* GraphQL */ `
  subscription OnDeleteMessage($filter: ModelSubscriptionMessageFilterInput) {
    onDeleteMessage(filter: $filter) {
      id
      text
      user {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      chatRoom {
        id
        createdAt
        updatedAt
        chatRoomMemberId
        chatRoomCoachId
        __typename
      }
      createdAt
      updatedAt
      messageUserId
      messageChatRoomId
      __typename
    }
  }
`;
export const onCreateChatRoom = /* GraphQL */ `
  subscription OnCreateChatRoom($filter: ModelSubscriptionChatRoomFilterInput) {
    onCreateChatRoom(filter: $filter) {
      id
      member {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      createdAt
      updatedAt
      chatRoomMemberId
      chatRoomCoachId
      __typename
    }
  }
`;
export const onUpdateChatRoom = /* GraphQL */ `
  subscription OnUpdateChatRoom($filter: ModelSubscriptionChatRoomFilterInput) {
    onUpdateChatRoom(filter: $filter) {
      id
      member {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      createdAt
      updatedAt
      chatRoomMemberId
      chatRoomCoachId
      __typename
    }
  }
`;
export const onDeleteChatRoom = /* GraphQL */ `
  subscription OnDeleteChatRoom($filter: ModelSubscriptionChatRoomFilterInput) {
    onDeleteChatRoom(filter: $filter) {
      id
      member {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      createdAt
      updatedAt
      chatRoomMemberId
      chatRoomCoachId
      __typename
    }
  }
`;
export const onCreateRating = /* GraphQL */ `
  subscription OnCreateRating($filter: ModelSubscriptionRatingFilterInput) {
    onCreateRating(filter: $filter) {
      id
      rating
      description
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      member {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      session_id {
        id
        appointment_date
        session_time
        session_incorporate_time
        session_slot
        location
        trainingType
        coachID
        status
        reason
        createdByID
        createdByIDCoach
        paymentStatus
        createdAt
        updatedAt
        __typename
      }
      createdAt
      updatedAt
      ratingCoachId
      ratingMemberId
      ratingSession_idId
      __typename
    }
  }
`;
export const onUpdateRating = /* GraphQL */ `
  subscription OnUpdateRating($filter: ModelSubscriptionRatingFilterInput) {
    onUpdateRating(filter: $filter) {
      id
      rating
      description
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      member {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      session_id {
        id
        appointment_date
        session_time
        session_incorporate_time
        session_slot
        location
        trainingType
        coachID
        status
        reason
        createdByID
        createdByIDCoach
        paymentStatus
        createdAt
        updatedAt
        __typename
      }
      createdAt
      updatedAt
      ratingCoachId
      ratingMemberId
      ratingSession_idId
      __typename
    }
  }
`;
export const onDeleteRating = /* GraphQL */ `
  subscription OnDeleteRating($filter: ModelSubscriptionRatingFilterInput) {
    onDeleteRating(filter: $filter) {
      id
      rating
      description
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      member {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      session_id {
        id
        appointment_date
        session_time
        session_incorporate_time
        session_slot
        location
        trainingType
        coachID
        status
        reason
        createdByID
        createdByIDCoach
        paymentStatus
        createdAt
        updatedAt
        __typename
      }
      createdAt
      updatedAt
      ratingCoachId
      ratingMemberId
      ratingSession_idId
      __typename
    }
  }
`;
export const onCreateBanner = /* GraphQL */ `
  subscription OnCreateBanner($filter: ModelSubscriptionBannerFilterInput) {
    onCreateBanner(filter: $filter) {
      id
      title
      image
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateBanner = /* GraphQL */ `
  subscription OnUpdateBanner($filter: ModelSubscriptionBannerFilterInput) {
    onUpdateBanner(filter: $filter) {
      id
      title
      image
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteBanner = /* GraphQL */ `
  subscription OnDeleteBanner($filter: ModelSubscriptionBannerFilterInput) {
    onDeleteBanner(filter: $filter) {
      id
      title
      image
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateCategoryDetail = /* GraphQL */ `
  subscription OnCreateCategoryDetail(
    $filter: ModelSubscriptionCategoryDetailFilterInput
  ) {
    onCreateCategoryDetail(filter: $filter) {
      id
      image
      title
      timing
      calories
      bodyType
      type
      Category {
        id
        title
        image
        tag
        createdAt
        updatedAt
        categoryCategoryDetailId
        __typename
      }
      createdAt
      updatedAt
      categoryDetailCategoryId
      __typename
    }
  }
`;
export const onUpdateCategoryDetail = /* GraphQL */ `
  subscription OnUpdateCategoryDetail(
    $filter: ModelSubscriptionCategoryDetailFilterInput
  ) {
    onUpdateCategoryDetail(filter: $filter) {
      id
      image
      title
      timing
      calories
      bodyType
      type
      Category {
        id
        title
        image
        tag
        createdAt
        updatedAt
        categoryCategoryDetailId
        __typename
      }
      createdAt
      updatedAt
      categoryDetailCategoryId
      __typename
    }
  }
`;
export const onDeleteCategoryDetail = /* GraphQL */ `
  subscription OnDeleteCategoryDetail(
    $filter: ModelSubscriptionCategoryDetailFilterInput
  ) {
    onDeleteCategoryDetail(filter: $filter) {
      id
      image
      title
      timing
      calories
      bodyType
      type
      Category {
        id
        title
        image
        tag
        createdAt
        updatedAt
        categoryCategoryDetailId
        __typename
      }
      createdAt
      updatedAt
      categoryDetailCategoryId
      __typename
    }
  }
`;
export const onCreateBookSession = /* GraphQL */ `
  subscription OnCreateBookSession(
    $filter: ModelSubscriptionBookSessionFilterInput
  ) {
    onCreateBookSession(filter: $filter) {
      id
      appointment_date
      session_time
      session_incorporate_time
      session_slot
      location
      trainingType
      coachID
      status
      reason
      createdByID
      createdByIDCoach
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      created_by_id {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      paymentStatus
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateBookSession = /* GraphQL */ `
  subscription OnUpdateBookSession(
    $filter: ModelSubscriptionBookSessionFilterInput
  ) {
    onUpdateBookSession(filter: $filter) {
      id
      appointment_date
      session_time
      session_incorporate_time
      session_slot
      location
      trainingType
      coachID
      status
      reason
      createdByID
      createdByIDCoach
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      created_by_id {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      paymentStatus
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteBookSession = /* GraphQL */ `
  subscription OnDeleteBookSession(
    $filter: ModelSubscriptionBookSessionFilterInput
  ) {
    onDeleteBookSession(filter: $filter) {
      id
      appointment_date
      session_time
      session_incorporate_time
      session_slot
      location
      trainingType
      coachID
      status
      reason
      createdByID
      createdByIDCoach
      coach {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      created_by_id {
        id
        username
        name
        email
        image
        age
        bio
        phone
        address
        country
        state
        city
        category
        working_radius
        hourly_rate
        cancellation_charge
        primary_id
        secondary_id
        coaching_certificate
        gender
        height
        weight
        traget_weight
        banner
        currency
        current_activity_lebel
        meal_routine
        login_provider
        role
        status
        user_id
        experience
        expoToken
        totalRating
        totalReview
        userStatus
        isVerified
        accountId
        isPaymentVerified
        isAdminStatus
        createdAt
        updatedAt
        __typename
      }
      paymentStatus
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateCategory = /* GraphQL */ `
  subscription OnCreateCategory($filter: ModelSubscriptionCategoryFilterInput) {
    onCreateCategory(filter: $filter) {
      id
      title
      image
      tag
      CategoryDetail {
        id
        image
        title
        timing
        calories
        bodyType
        type
        createdAt
        updatedAt
        categoryDetailCategoryId
        __typename
      }
      createdAt
      updatedAt
      categoryCategoryDetailId
      __typename
    }
  }
`;
export const onUpdateCategory = /* GraphQL */ `
  subscription OnUpdateCategory($filter: ModelSubscriptionCategoryFilterInput) {
    onUpdateCategory(filter: $filter) {
      id
      title
      image
      tag
      CategoryDetail {
        id
        image
        title
        timing
        calories
        bodyType
        type
        createdAt
        updatedAt
        categoryDetailCategoryId
        __typename
      }
      createdAt
      updatedAt
      categoryCategoryDetailId
      __typename
    }
  }
`;
export const onDeleteCategory = /* GraphQL */ `
  subscription OnDeleteCategory($filter: ModelSubscriptionCategoryFilterInput) {
    onDeleteCategory(filter: $filter) {
      id
      title
      image
      tag
      CategoryDetail {
        id
        image
        title
        timing
        calories
        bodyType
        type
        createdAt
        updatedAt
        categoryDetailCategoryId
        __typename
      }
      createdAt
      updatedAt
      categoryCategoryDetailId
      __typename
    }
  }
`;
export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser($filter: ModelSubscriptionUserFilterInput) {
    onCreateUser(filter: $filter) {
      id
      username
      name
      email
      image
      age
      bio
      phone
      address
      country
      state
      city
      category
      working_radius
      hourly_rate
      cancellation_charge
      primary_id
      secondary_id
      coaching_certificate
      gender
      height
      weight
      traget_weight
      banner
      currency
      current_activity_lebel
      meal_routine
      login_provider
      role
      status
      user_id
      experience
      BookSessions {
        nextToken
        __typename
      }
      BookSessionsCoach {
        nextToken
        __typename
      }
      expoToken
      totalRating
      totalReview
      userStatus
      isVerified
      accountId
      isPaymentVerified
      isAdminStatus
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser($filter: ModelSubscriptionUserFilterInput) {
    onUpdateUser(filter: $filter) {
      id
      username
      name
      email
      image
      age
      bio
      phone
      address
      country
      state
      city
      category
      working_radius
      hourly_rate
      cancellation_charge
      primary_id
      secondary_id
      coaching_certificate
      gender
      height
      weight
      traget_weight
      banner
      currency
      current_activity_lebel
      meal_routine
      login_provider
      role
      status
      user_id
      experience
      BookSessions {
        nextToken
        __typename
      }
      BookSessionsCoach {
        nextToken
        __typename
      }
      expoToken
      totalRating
      totalReview
      userStatus
      isVerified
      accountId
      isPaymentVerified
      isAdminStatus
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser($filter: ModelSubscriptionUserFilterInput) {
    onDeleteUser(filter: $filter) {
      id
      username
      name
      email
      image
      age
      bio
      phone
      address
      country
      state
      city
      category
      working_radius
      hourly_rate
      cancellation_charge
      primary_id
      secondary_id
      coaching_certificate
      gender
      height
      weight
      traget_weight
      banner
      currency
      current_activity_lebel
      meal_routine
      login_provider
      role
      status
      user_id
      experience
      BookSessions {
        nextToken
        __typename
      }
      BookSessionsCoach {
        nextToken
        __typename
      }
      expoToken
      totalRating
      totalReview
      userStatus
      isVerified
      accountId
      isPaymentVerified
      isAdminStatus
      createdAt
      updatedAt
      __typename
    }
  }
`;
